### ISSUE TITLE
Active for full url doesn't work

### ISSUE THREAD

**Issue by riasvdv** [barrelstrength/sprout-active#1]
Trying to check for active with a full url doesn't work on Craft RC10, getting the following error:

![afbeelding](https://user-images.githubusercontent.com/3626559/36196736-f470da80-1171-11e8-9dbd-e93d8b3c6bb7.png)

**Comment by BenParizek** [comment]
Thanks @Rias500. We'll look into it.

**Comment by BenParizek** [comment]
Thanks for reporting @Rias500. Fixed in v2.0.4 and just released.
