### ISSUE TITLE
Absolute URL setting doesn't work if an alias is used

### ISSUE THREAD

**Issue by BenParizek** [barrelstrength/sprout-active#4]
This works fine if Base URL is set to `https://website.com/` but fails if Base URL is set to `@web/`

{{ active('https://website.com/news/article', 'url') }}

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_dmwb)

**Comment by pdaleramirez** [comment]
Committed a fix for this https://github.com/barrelstrength/craft-sprout-active/commit/59f4abfbfdfdc09241c84e26bf2ca608f4b20ee6

**Comment by BenParizek** [comment]
@pdaleramirez We're going to need to handle the @web Yii alias dynamically. Users can define and use custom values like @baseUrl or @whatever too.

**Comment by jsunsawyer** [comment]
I'm trying to get this to work with a nav built using linkIt fields in a matrix field. Because of this, I need to use absolute URLs.

I attempted to use `path` as an alternate solution, but just get an `Unknown Property` error.

Here's what I'm attempting to add `{{ active(navLink.url|replace(siteUrl, ''), 'path', 'is-active') }}`

**Comment by BenParizek** [comment]
@jsunsawyer Looks like we had another bug when testing for `path`. I've pushed a fix in v2.0.8 which is now available in the plugin store.

**Comment by pdaleramirez** [comment]
Added support for alias based string for url active here https://github.com/barrelstrength/craft-sprout-active/commit/0696d8e453b09f031f5e52bd38a9d0100bd20c89

**Comment by BenParizek** [comment]
This is resolved in release v2.0.9, now in the plugin store.
