### ISSUE TITLE
Adding space before class='active'

### ISSUE THREAD

**Issue by jayhlee** [barrelstrength/sprout-active#5]
Is there a way to add a space before the output of `class="active"`? Right now, I have to code in a space like this:

`<li><a href="xyz" {{ activeClass('xyz') }}>XYZ</a></li>`

If the link is not a matching class, however, there's an extra space like this, which is what I'd like to avoid:

`<li><a href="xyz" >XYZ</a></li>`

**Comment by BenParizek** [comment]
@jayhlee A few options:

Sprout Active has another function that just outputs the word `active` and can also be used in conditionals. In this case, the space has been moved to inside the conditional:

```
<li><a href="xyz"{% if active('xyz') %} {{ activeClass('xyz') }}{% endif %}>XYZ</a></li>
```

I haven't explored it too closely, but it may be fairly tricky for us to make more assumptions about where and how the active class is being output and how to adjust spacing proactively. The conditional logic is probably the best solution alongside other general use cases.

There might be some other techniques you could consider as well like minifying all of your html and removing the whitespaces that way.
